language: 'python'
python:
  - '3.7'

before_install:
  - 'pip install setuptools pytest'

install:
  - 'pip install -e .'

script:
  - 'cd ./example; npm install; npm run build;'
  - 'py.test example/tests'