matrix:
  include:
    - language: node_js
      node_js:
        - 12
      before_install:
        'cd ./example/'
      install:
        - 'npm install'
        - 'npm run build'

    - language: python
      python:
        - 3.7
      before_install:
        - 'pip install setuptools pytest'

      install:
        - 'pip install -e .'

      script:
        - 'py.test example/tests'
